# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JustGo
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'JustGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustGoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
